AWSTemplateFormatVersion: '2010-09-09'
Description: Cria NAT Gateway e define rota em tabela de rotas existente

Parameters:
  PubSubnetId:
    Type: String
    Description: Sub-rede pública onde o NAT será criado
  RouteTableId:
    Type: String
    Description: Tabela de rotas privada já existente
  VpcId:
    Type: String
    Description: ID da VPC existente

Resources:
  Ip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt Ip.AllocationId
      SubnetId: !Ref PubSubnetId

  RotaTabelaPriv:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableId
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
